### ISSUE TITLE
CSS选择器

### ISSUE THREAD

**Issue by wittyResry** [wittyResry/myIssue#44]
问题1：[CSS中定义CLASS时，中间有空格和没空格的区别是什么？](https://segmentfault.com/q/1010000003881922)
```css
.example .pp{
  color: orange;
}
.example.pp2 {
  color: green;
}
```

.example .pp = E F 是后代选择器。
.example.pp2 则是在一个元素上，这个元素包括这两个类才会有效果。
